audio:
  auto_gain_control: true
  channels: 1
  chunk_interval: 10
  chunk_size:
  - 5
  - 10
  - 5
  decoder_chunk_look_back: 0
  device_id: null
  device_name: null
  encoder_chunk_look_back: 4
  input_buffer_size: 4096
  noise_suppression: true
  sample_rate: 16000
config_version: '1.0'
hotkey:
  conflict_detection: true
  enable_sound_feedback: true
  mode: press_and_hold
  modifier_keys:
  - ctrl
  - alt
  stop_key: ctrl+alt+space
  trigger_key: ctrl+alt+space
logging:
  backup_count: 5
  console_output: true
  file_path: null
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
recognition:
  capture_mode: hotkey
  hotword_file: null
  hotwords: []
  language_model: zh-cn
  mode: 2pass
  output_dir: null
  use_itn: true
  use_punctuation: true
  words_max_print: 10000
server:
  host: localhost
  port: 10095
  reconnect_attempts: 3
  reconnect_interval: 2.0
  ssl_verify: false
  timeout: 30.0
  use_ssl: true
text_injection:
  auto_inject: true
  compatible_apps: []
  cursor_positioning: end
  fallback_to_clipboard: false
  format_text: true
  ime_config:
    auto_detect_ime: true
    composition_timeout: 1.0
    dbus_timeout: 2.0
    debug_mode: false
    enabled: true
    fallback_timeout: 5.0
    linux_ime_frameworks:
    - fcitx5
    - ibus
    - fcitx
    preferred_framework: null
    state_monitor_interval: 0.1
  ime_debug: false
  ime_frameworks:
  - fcitx5
  - ibus
  - fcitx
  incompatible_apps: []
  inject_delay: 0.1
  strip_whitespace: true
  use_ime: true
ui:
  auto_start: false
  language: zh_CN
  minimize_to_tray: true
  notification_duration: 3.0
  show_notifications: true
  show_tray_icon: true
  tray_icon_theme: auto
user_data_dir: /home/decker/.config/nextalk
version: 0.1.0
